java:
  applicationPort: 4553
  image: 'hmctspublic.azurecr.io/opal/legacy-db-stub:latest'
  ingressHost: opal-legacy-db-stub-{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: opal
  keyVaults:
    opal:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: app-insights-connection-string
          alias: app-insights-connection-string
  environment:
    WIREMOCK_USE_HTTPS: false
